#!/bin/bash
# ==============================================================================
# generate_mpirun.sh
# Generates a bash script running all cases locally with mpirun
# (pure MPI and/or multi-thread)
#
# Usage:
#   ./generate_mpirun.sh -e <executable> [OPTIONS]
#
# Options:
#   -e <path>          Path to executable (mandatory, resolved to absolute path)
#   -p <label>         Label used in listing filenames  (default: local)
#   -a <args>          Extra arguments for the executable (default: none)
#   -n <tasks/node>    MPI tasks per node / max threads  (default: 288)
#   -o <file>          Output script name               (default: run_all.sh)
#   -M                 Generate pure MPI cases          (default: both)
#   -T                 Generate multi-thread cases      (default: both)
#   -h                 Show this help
# ==============================================================================

# --- Default parameters ---
LABEL="local"
EXECUTABLE=""
EXE_ARGS=""
NTASKS_PER_NODE=288
OUTPUT_SCRIPT="run_all.sh"
DO_MPI=1
DO_MT=1
# --------------------------

usage() {
    sed -n '/^# Usage/,/^# ====/p' "$0" | sed 's/^# \{0,3\}//'
    exit 0
}

while getopts ":p:e:a:n:o:MTh" opt; do
    case $opt in
        p) LABEL="$OPTARG" ;;
        e) EXECUTABLE="$OPTARG" ;;
        a) EXE_ARGS="$OPTARG" ;;
        n) NTASKS_PER_NODE="$OPTARG" ;;
        o) OUTPUT_SCRIPT="$OPTARG" ;;
        M) DO_MPI=1; DO_MT=0 ;;
        T) DO_MPI=0; DO_MT=1 ;;
        h) usage ;;
        :) echo "ERROR: option -$OPTARG requires an argument."; exit 1 ;;
        \?) echo "ERROR: unknown option -$OPTARG"; exit 1 ;;
    esac
done

# --- Validate mandatory -e option ---
if [[ -z "$EXECUTABLE" ]]; then
    echo "ERROR: option -e <path> is mandatory."
    echo "Usage: $0 -e <path/to/executable> [OPTIONS]"
    exit 1
fi

EXECUTABLE=$(realpath "$EXECUTABLE" 2>/dev/null)
if [[ $? -ne 0 ]]; then
    echo "ERROR: cannot resolve executable path."
    exit 1
fi

if [[ ! -x "$EXECUTABLE" ]]; then
    echo "ERROR: executable not found or not executable: $EXECUTABLE"
    exit 1
fi

echo "=== generate_mpirun.sh ==="
echo "  Label           : $LABEL"
echo "  Executable      : $EXECUTABLE"
echo "  Extra args      : ${EXE_ARGS:-(none)}"
echo "  Tasks/node      : $NTASKS_PER_NODE"
echo "  Output script   : $OUTPUT_SCRIPT"
echo "  Pure MPI        : $([ $DO_MPI -eq 1 ] && echo yes || echo no)"
echo "  Multi-thread    : $([ $DO_MT  -eq 1 ] && echo yes || echo no)"
echo ""

shopt -s nullglob

# --- Collect pure MPI cases ---
mpi_files=(Donnees*_nsd_*.arc)
declare -a mpi_cases   # each entry: "arc_file nprocs nx ny nz"

if [[ $DO_MPI -eq 1 ]]; then
    if [[ ${#mpi_files[@]} -eq 0 ]]; then
        echo "WARNING: no file matching Donnees*_nsd_*.arc found, skipping MPI cases."
        DO_MPI=0
    else
        for arc_file in "${mpi_files[@]}"; do
            basename_noext="${arc_file%.arc}"
            nsd_part=$(echo "$basename_noext" | grep -oP '\d+x\d+x\d+')
            [[ -z "$nsd_part" ]] && continue
            IFS='x' read -r nx ny nz <<< "$nsd_part"
            nprocs=$(( 10#$nx * 10#$ny * 10#$nz ))
            mpi_cases+=("${arc_file} ${nprocs} ${nx} ${ny} ${nz}")
        done
    fi
fi

# --- Collect multi-thread cases ---
ref_files=(Donnees*_nsd_01x01x01.arc)
declare -a mt_cases    # each entry: "arc_file ncores"

if [[ $DO_MT -eq 1 ]]; then
    if [[ ${#ref_files[@]} -eq 0 ]]; then
        echo "WARNING: no file matching Donnees*_nsd_01x01x01.arc found, skipping multi-thread cases."
        DO_MT=0
    else
        # Collect ncores values from all nsd files
        declare -A seen_ncores
        for arc_file in "${mpi_files[@]}"; do
            basename_noext="${arc_file%.arc}"
            nsd_part=$(echo "$basename_noext" | grep -oP '\d+x\d+x\d+')
            [[ -z "$nsd_part" ]] && continue
            IFS='x' read -r nx ny nz <<< "$nsd_part"
            ncores=$(( 10#$nx * 10#$ny * 10#$nz ))
            seen_ncores[$ncores]=1
        done

        for ref_arc in "${ref_files[@]}"; do
            for ncores in $(echo "${!seen_ncores[@]}" | tr ' ' '\n' | sort -n); do
                mt_cases+=("${ref_arc} ${ncores}")
            done
        done
    fi
fi

if [[ ${#mpi_cases[@]} -eq 0 && ${#mt_cases[@]} -eq 0 ]]; then
    echo "ERROR: no cases to generate."
    exit 1
fi

# ==============================================================================
# Write the output script
# ==============================================================================
cat > "$OUTPUT_SCRIPT" <<'HEADER'
#!/bin/bash
# ==============================================================================
# run_all.sh  --  generated by generate_mpirun.sh
# Runs all cases sequentially with mpirun.
# Usage: ./run_all.sh
# ==============================================================================

set -euo pipefail

log() { echo "[$(date '+%H:%M:%S')] $*"; }

HEADER

# Inject resolved settings as variables at the top
cat >> "$OUTPUT_SCRIPT" <<EOF
EXECUTABLE="${EXECUTABLE}"
EXE_ARGS="${EXE_ARGS}"

EOF

# --- Pure MPI section ---
if [[ $DO_MPI -eq 1 && ${#mpi_cases[@]} -gt 0 ]]; then
    echo "# --- Pure MPI cases ---" >> "$OUTPUT_SCRIPT"
    echo "" >> "$OUTPUT_SCRIPT"

    for entry in "${mpi_cases[@]}"; do
        read -r arc_file nprocs nx ny nz <<< "$entry"
        nprocs_fmt=$(printf "%03d" "$nprocs")
        listing="listing_${LABEL}_n${nprocs_fmt}"

        if [[ -n "$EXE_ARGS" ]]; then
            run_cmd="\${EXECUTABLE} ${arc_file} \${EXE_ARGS}"
        else
            run_cmd="\${EXECUTABLE} ${arc_file}"
        fi

        cat >> "$OUTPUT_SCRIPT" <<EOF
log "MPI  | file=${arc_file}  nprocs=${nprocs}  nsd=${nx}x${ny}x${nz}"
mpirun -n ${nprocs} ${run_cmd} > ${listing}
log "done | listing=${listing}"

EOF
    done
fi

# --- Multi-thread section ---
if [[ $DO_MT -eq 1 && ${#mt_cases[@]} -gt 0 ]]; then
    echo "# --- Multi-thread cases ---" >> "$OUTPUT_SCRIPT"
    echo "" >> "$OUTPUT_SCRIPT"

    for entry in "${mt_cases[@]}"; do
        read -r ref_arc ncores <<< "$entry"
        ncores_fmt=$(printf "%03d" "$ncores")
        listing="listing_${LABEL}_k${ncores_fmt}"

        if [[ -n "$EXE_ARGS" ]]; then
            run_cmd="\${EXECUTABLE} -A,T=${ncores} ${ref_arc} \${EXE_ARGS}"
        else
            run_cmd="\${EXECUTABLE} -A,T=${ncores} ${ref_arc}"
        fi

        cat >> "$OUTPUT_SCRIPT" <<EOF
log "MT   | file=${ref_arc}  ncores=${ncores}"
mpirun -n 1 -x OMP_NUM_THREADS=${ncores} ${run_cmd} > ${listing}
log "done | listing=${listing}"

EOF
    done
fi

cat >> "$OUTPUT_SCRIPT" <<'FOOTER'
log "All cases completed."
FOOTER

chmod +x "$OUTPUT_SCRIPT"

nmpi=${#mpi_cases[@]}
nmt=${#mt_cases[@]}
echo "  [OK] $OUTPUT_SCRIPT  ($nmpi MPI case(s), $nmt multi-thread case(s))"
echo ""
echo ">>> Run with: ./$OUTPUT_SCRIPT"
