#!/bin/bash
# ==============================================================================
# generate_mpirun.sh
# Generates a bash script running all cases locally with mpirun
# (pure MPI and/or multi-thread)
#
# Usage:
#   ./generate_mpirun.sh -e <executable> [OPTIONS]
#
# Options:
#   -e <path>          Path to executable (mandatory, resolved to absolute path)
#   -p <partition>     TGCC partition                    (default: gh200-bxi)
#   -a <args>          Extra arguments for the executable (default: none)
#   -o <file>          Output script name               (default: run_all.sh)
#   -M                 Generate pure MPI cases only     (default: both)
#   -T                 Generate multi-thread cases only (default: both)
#   -h                 Show this help
# ==============================================================================

# --- Default parameters ---
PARTITION="gh200-bxi"
EXECUTABLE=""
EXE_ARGS=""
OUTPUT_SCRIPT="run_all.sh"
DO_MPI=1
DO_MT=1
# --------------------------

usage() {
    sed -n '/^# Usage/,/^# ====/p' "$0" | sed 's/^# \{0,3\}//'
    exit 0
}

while getopts ":p:e:a:n:o:MTh" opt; do
    case $opt in
        p) PARTITION="$OPTARG" ;;
        e) EXECUTABLE="$OPTARG" ;;
        a) EXE_ARGS="$OPTARG" ;;
        o) OUTPUT_SCRIPT="$OPTARG" ;;
        M) DO_MPI=1; DO_MT=0 ;;
        T) DO_MPI=0; DO_MT=1 ;;
        h) usage ;;
        :) echo "ERROR: option -$OPTARG requires an argument."; exit 1 ;;
        \?) echo "ERROR: unknown option -$OPTARG"; exit 1 ;;
    esac
done

# --- Validate mandatory -e option ---
if [[ -z "$EXECUTABLE" ]]; then
    echo "ERROR: option -e <path> is mandatory."
    echo "Usage: $0 -e <path/to/executable> [OPTIONS]"
    exit 1
fi

EXECUTABLE=$(realpath "$EXECUTABLE" 2>/dev/null)
if [[ $? -ne 0 ]]; then
    echo "ERROR: cannot resolve executable path."
    exit 1
fi

if [[ ! -x "$EXECUTABLE" ]]; then
    echo "ERROR: executable not found or not executable: $EXECUTABLE"
    exit 1
fi

echo "=== generate_mpirun.sh ==="
echo "  PARTITION       : $PARTITION"
echo "  Executable      : $EXECUTABLE"
echo "  Extra args      : ${EXE_ARGS:-(none)}"
echo "  Output script   : $OUTPUT_SCRIPT"
echo "  Pure MPI        : $([ $DO_MPI -eq 1 ] && echo yes || echo no)"
echo "  Multi-thread    : $([ $DO_MT  -eq 1 ] && echo yes || echo no)"
echo ""

shopt -s nullglob
all_files=(Donnees*_nsd_*.arc)

if [[ ${#all_files[@]} -eq 0 ]]; then
    echo "ERROR: no file matching Donnees*_nsd_*.arc found in $(pwd)"
    exit 1
fi

# ==============================================================================
# Write the output script header
# ==============================================================================
cat > "$OUTPUT_SCRIPT" <<HEADER
#!/bin/bash
# ==============================================================================
# ${OUTPUT_SCRIPT}  --  generated by generate_mpirun.sh
# Runs all cases sequentially with mpirun.
# Usage: ./${OUTPUT_SCRIPT}
# ==============================================================================

set -euo pipefail

log() { echo "[\$(date '+%H:%M:%S')] \$*"; }

EXECUTABLE="${EXECUTABLE}"
EXE_ARGS="${EXE_ARGS}"

module load c++/gcc/12 cuda/12.4 hdf5/1.14.3 mpi/openmpi/4.1.7

HEADER

nmpi=0
nmt=0

for arc_file in "${all_files[@]}"; do
    basename_noext="${arc_file%.arc}"
    nsd_part=$(echo "$basename_noext" | grep -oP '\d+x\d+x\d+')
    [[ -z "$nsd_part" ]] && continue

    IFS='x' read -r nx ny nz <<< "$nsd_part"
    nprocs=$(( 10#$nx * 10#$ny * 10#$nz ))
    nprocs_fmt=$(printf "%03d" "$nprocs")

    # Pure MPI case
    if [[ $DO_MPI -eq 1 ]]; then
        listing="listing_${PARTITION}_n${nprocs_fmt}"
        if [[ -n "$EXE_ARGS" ]]; then
            mpi_run_cmd="\${EXECUTABLE} ${arc_file} \${EXE_ARGS}"
        else
            mpi_run_cmd="\${EXECUTABLE} ${arc_file}"
        fi
        cat >> "$OUTPUT_SCRIPT" <<EOF
log "MPI  | file=${arc_file}  nprocs=${nprocs}  nsd=${nx}x${ny}x${nz}"
mpirun -n ${nprocs} ${mpi_run_cmd} > ${listing}
log "done | listing=${listing}"

EOF
        (( nmpi++ ))
    fi

    # Multi-thread case: same .arc file, -n 1 -x OMP_NUM_THREADS=<nprocs>
    # Insert -A,T=<ncores> right after the binary
    if [[ $DO_MT -eq 1 ]]; then
        listing="listing_${PARTITION}_k${nprocs_fmt}"
        if [[ -n "$EXE_ARGS" ]]; then
            mt_run_cmd="\${EXECUTABLE} -A,T=${nprocs} ${arc_file} \${EXE_ARGS}"
        else
            mt_run_cmd="\${EXECUTABLE} -A,T=${nprocs} ${arc_file}"
        fi
        cat >> "$OUTPUT_SCRIPT" <<EOF
log "MT   | file=${arc_file}  ncores=${nprocs}  nsd=${nx}x${ny}x${nz}"
mpirun -n 1 -x OMP_NUM_THREADS=${nprocs} ${mt_run_cmd} > ${listing}
log "done | listing=${listing}"

EOF
        (( nmt++ ))
    fi
done

cat >> "$OUTPUT_SCRIPT" <<'FOOTER'
log "All cases completed."
FOOTER

chmod +x "$OUTPUT_SCRIPT"

echo "  [OK] $OUTPUT_SCRIPT  ($nmpi MPI case(s), $nmt multi-thread case(s))"
echo ""
echo ">>> Run with: ./$OUTPUT_SCRIPT"
