#!/bin/bash
# ==============================================================================
# submit_all.sh
# Submits all job_*.msub files generated by generate_msub.sh
# TGCC environment (ccc_msub)
#
# Usage:
#   ./submit_all.sh [OPTIONS]
#
# Options:
#   -d    Dry-run: print ccc_msub commands without executing them
#   -h    Show this help
# ==============================================================================

DRY_RUN=0

usage() {
    sed -n '/^# Usage/,/^# ====/p' "$0" | sed 's/^# \{0,3\}//'
    exit 0
}

while getopts ":dh" opt; do
    case $opt in
        d) DRY_RUN=1 ;;
        h) usage ;;
        \?) echo "ERROR: unknown option -$OPTARG"; exit 1 ;;
    esac
done

if [[ $DRY_RUN -eq 1 ]]; then
    echo ">>> DRY-RUN mode: jobs will not be submitted."
    echo ""
fi

shopt -s nullglob
msub_files=(job_Donnees*.msub)

if [[ ${#msub_files[@]} -eq 0 ]]; then
    echo "ERROR: no file matching job_Donnees*.msub found in $(pwd)"
    echo "Run ./generate_msub.sh first."
    exit 1
fi

echo ">>> ${#msub_files[@]} job(s) to submit"
echo ""

submitted=0
failed=0

for msub in "${msub_files[@]}"; do
    if [[ $DRY_RUN -eq 1 ]]; then
        echo "  [DRY-RUN] ccc_msub $msub"
    else
        output=$(ccc_msub "$msub" 2>&1)
        if [[ $? -eq 0 ]]; then
            job_id=$(echo "$output" | grep -oP '\d+')
            echo "  [SUBMITTED] $msub  -->  Job ID: ${job_id}"
            (( submitted++ ))
        else
            echo "  [ERROR] $msub  :  $output"
            (( failed++ ))
        fi
    fi
done

echo ""
if [[ $DRY_RUN -eq 0 ]]; then
    echo ">>> Result: ${submitted} job(s) submitted, ${failed} error(s)."
    echo ""
    echo "Monitor: ccc_mpp -u \$USER"
    echo "         ccc_macct -u \$USER"
fi
