#!/bin/bash
# ==============================================================================
# submit_all.sh
# Submits all job_*.msub files generated by generate_msub.sh
# TGCC environment (ccc_msub)
# Waits when the number of pending/running jobs reaches the limit.
#
# Usage:
#   ./submit_all.sh [OPTIONS]
#
# Options:
#   -d         Dry-run: print ccc_msub commands without executing them
#   -l <N>     Max number of concurrent jobs in queue (default: 5)
#   -w <sec>   Polling interval in seconds when queue is full (default: 60)
#   -h         Show this help
# ==============================================================================

DRY_RUN=0
MAX_JOBS=5
POLL_INTERVAL=60

usage() {
    sed -n '/^# Usage/,/^# ====/p' "$0" | sed 's/^# \{0,3\}//'
    exit 0
}

while getopts ":dl:w:h" opt; do
    case $opt in
        d) DRY_RUN=1 ;;
        l) MAX_JOBS="$OPTARG" ;;
        w) POLL_INTERVAL="$OPTARG" ;;
        h) usage ;;
        :) echo "ERROR: option -$OPTARG requires an argument."; exit 1 ;;
        \?) echo "ERROR: unknown option -$OPTARG"; exit 1 ;;
    esac
done

# Return the list of our submitted job IDs still present in the queue
active_ids() {
    local queue_ids
    queue_ids=$(ccc_mpp -u "$USER" 2>/dev/null | awk 'NR>1 {print $3}')
    local id
    for id in "${submitted_ids[@]}"; do
        if echo "$queue_ids" | grep -qx "$id"; then
            echo "$id"
        fi
    done
}

# Wait until fewer than MAX_JOBS of our submitted jobs are active.
# Strategy: after each submission, we know the real count is at least
# (number we just submitted). We poll ccc_mpp and only proceed when
# the queue confirms enough slots are free.
wait_for_slot() {
    while true; do
        local alive
        alive=$(active_ids | wc -l)
        if [[ $alive -lt $MAX_JOBS ]]; then
            return
        fi
        echo "  [WAIT] ${alive} job(s) active (limit=${MAX_JOBS}), waiting ${POLL_INTERVAL}s..."
        sleep "$POLL_INTERVAL"
    done
}

if [[ $DRY_RUN -eq 1 ]]; then
    echo ">>> DRY-RUN mode: jobs will not be submitted."
    echo ""
fi

shopt -s nullglob
msub_files=(job_Donnees*.msub)

if [[ ${#msub_files[@]} -eq 0 ]]; then
    echo "ERROR: no file matching job_Donnees*.msub found in $(pwd)"
    echo "Run ./generate_msub.sh first."
    exit 1
fi

echo ">>> ${#msub_files[@]} job(s) to submit (max ${MAX_JOBS} concurrent)"
echo ""

submitted=0
failed=0
declare -a submitted_ids   # job IDs successfully submitted

for msub in "${msub_files[@]}"; do
    if [[ $DRY_RUN -eq 1 ]]; then
        echo "  [DRY-RUN] ccc_msub $msub"
    else
        # Wait before submitting so we never exceed MAX_JOBS
        wait_for_slot
        output=$(ccc_msub "$msub" 2>&1)
        if [[ $? -eq 0 ]]; then
            job_id=$(echo "$output" | grep -oP '\d+')
            submitted_ids+=("$job_id")
            echo "  [SUBMITTED] $msub  -->  Job ID: ${job_id}"
            (( submitted++ ))
        else
            echo "  [ERROR] $msub  :  $output"
            (( failed++ ))
        fi
    fi
done

echo ""
if [[ $DRY_RUN -eq 0 ]]; then
    echo ">>> Result: ${submitted} job(s) submitted, ${failed} error(s)."
    echo ""
    echo "Monitor: ccc_mpp -u \$USER"
    echo "         ccc_macct -u \$USER"
fi
